query LabelsList {
  labelsList {
    items {
      label{
        id
        label
        color
        tasks{
          items{
            task{
              id
            }
          }
        }
      }
    }
  }
}
