query task($id: ID!) {
  task(id: $id) {
    id
    title
    description
    dueAt
    image {
      id
      downloadUrl
    }
    labels {
      items {
        id
        label
        color
        tasks{
          items{
            id
          }
        }
      }
    }
    comments {
      items {
        id
        message
      }
    }
  }
}